name    'tscopp-jss'
version '0.2.0'
source 'https://github.com/tscopp/puppet-jss/issues'
author 'tscopp'
license 'Apache License, Version 2.0'
summary 'JSS Puppet module'
description 'Puppet module to install and configure JAMF JSS and supporing database services.'
project_page 'https://github.com/tscopp/puppet-jss/'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/firewall', '>=1.8.0'
dependency 'puppetlabs/mysql', '>=3.7.0'
dependency 'puppetlabs/stdlib', '>=4.11.0'
